"""
JLAW Report Generator Agent
Produces formal research reports, SEC enforcement bundles, DOJ criminal referrals,
and legislative briefings from the anomaly database and parsed filing data.

Report types:
  master   — Master cross-analysis report (FY2019–FY2025)
  sec      — SEC Division of Enforcement submission bundle
  doj      — DOJ Fraud Section criminal referral package
  leg      — Congressional legislative briefing

Usage:
    python -m src.agents.report_generator --type master
    python -m src.agents.report_generator --type sec
    python -m src.agents.report_generator --type doj
    python -m src.agents.report_generator --type leg
"""

import argparse
import json
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional

from docx import Document
from docx.shared import Inches, Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT


# ═══════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = Path(os.environ.get("JLAW_DATA_DIR", PROJECT_ROOT / "data"))
ANOMALY_DIR = DATA_DIR / "anomalies"
PARSED_DIR = DATA_DIR / "parsed"
REPORTS_DIR = DATA_DIR / "reports"
LOG_DIR = Path(os.environ.get("JLAW_LOG_DIR", PROJECT_ROOT / "logs"))

# Claude Compositor integration — activated when ANTHROPIC_API_KEY is available
COMPOSITOR_AVAILABLE = False
try:
    from src.agents.claude_compositor import ClaudeCompositor
    if os.environ.get("ANTHROPIC_API_KEY"):
        COMPOSITOR_AVAILABLE = True
except ImportError:
    pass


def load_anomaly_db() -> Dict:
    """Load the anomaly database."""
    db_path = ANOMALY_DIR / "anomaly_database.json"
    if db_path.exists():
        with open(db_path) as f:
            return json.load(f)
    return {"anomalies": [], "patterns": []}


def load_deliverable_inventory() -> Dict:
    """Load the parsed deliverable inventory."""
    inv_path = PARSED_DIR / "deliverables" / "deliverable_inventory.json"
    if inv_path.exists():
        with open(inv_path) as f:
            return json.load(f)
    return {}


def add_title_page(doc: Document, title: str, subtitle: str, date: str,
                   classification: str = "PRIVILEGED & CONFIDENTIAL"):
    """Add a formatted title page to the document."""
    # Classification header
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(classification)
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(192, 0, 0)

    for _ in range(4):
        doc.add_paragraph()

    # Title
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(24)

    doc.add_paragraph()

    # Subtitle
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(subtitle)
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(89, 89, 89)

    for _ in range(3):
        doc.add_paragraph()

    # Meta info
    meta_lines = [
        f"Date: {date}",
        "Subject: Nike, Inc. (NKE) | CIK 0000320187",
        "Scope: FY2019 through Q1 CY2026",
        "Generated by: JLAW Agent Platform v5.0",
    ]
    for line in meta_lines:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(line)
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(89, 89, 89)

    doc.add_page_break()


def add_anomaly_table(doc: Document, anomalies: List[Dict], title: str = "Anomaly Summary"):
    """Add a table summarizing anomalies."""
    doc.add_heading(title, level=2)

    if not anomalies:
        doc.add_paragraph("No anomalies found in this category.")
        return

    table = doc.add_table(rows=1, cols=5)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Headers
    headers = ["ID", "Severity", "Fiscal Year", "Category", "Title"]
    for i, header in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = header
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.bold = True
                run.font.size = Pt(9)

    # Data rows
    for anomaly in anomalies:
        row = table.add_row()
        values = [
            anomaly.get("anomaly_id", ""),
            anomaly.get("severity", ""),
            anomaly.get("fiscal_year", ""),
            anomaly.get("category", ""),
            anomaly.get("title", "")[:80],
        ]
        for i, val in enumerate(values):
            row.cells[i].text = str(val)
            for paragraph in row.cells[i].paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(8)

    doc.add_paragraph()


def add_pattern_section(doc: Document, patterns: List[Dict], anomalies: List[Dict]):
    """Add compounding pattern analysis section."""
    doc.add_heading("Compounding Patterns", level=1)

    if not patterns:
        doc.add_paragraph("No compounding patterns identified.")
        return

    for pattern in patterns:
        doc.add_heading(f"{pattern['pattern_id']}: {pattern['title']}", level=2)
        doc.add_paragraph(pattern.get("description", ""))

        # List linked anomalies
        linked = [a for a in anomalies if a["anomaly_id"] in pattern.get("anomaly_ids", [])]
        if linked:
            doc.add_paragraph(
                f"Years spanned: {', '.join(pattern.get('years_spanned', []))}",
            )
            doc.add_paragraph(f"Linked anomalies: {len(linked)}")
            for a in linked:
                doc.add_paragraph(
                    f"  • {a['anomaly_id']}: {a['title']}",
                    style="List Bullet",
                )

        doc.add_paragraph()


# ═══════════════════════════════════════════════
# REPORT GENERATORS
# ═══════════════════════════════════════════════

def _render_composed_text(doc: Document, composed_text: str, heading_level: int = 2):
    """
    Render Claude-composed text into a DOCX document.
    Parses [SECTION: Title] and [EVIDENCE: ...] markers.
    """
    lines = composed_text.split("\n")
    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        # Parse section markers
        if stripped.startswith("[SECTION:") and stripped.endswith("]"):
            title = stripped[9:-1].strip()
            doc.add_heading(title, level=heading_level)
        elif stripped.startswith("[EVIDENCE:") and stripped.endswith("]"):
            ev_text = stripped[10:-1].strip()
            p = doc.add_paragraph()
            run = p.add_run(f"📎 Evidence: {ev_text}")
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(89, 89, 89)
            run.italic = True
        elif stripped.startswith("[HUMAN REVIEW REQUIRED]"):
            p = doc.add_paragraph()
            run = p.add_run("⚠ HUMAN REVIEW REQUIRED")
            run.bold = True
            run.font.color.rgb = RGBColor(192, 0, 0)
        else:
            doc.add_paragraph(stripped)


def _load_precomposed(label: str) -> Optional[Dict]:
    """Load a pre-composed section set from the Compositor output cache."""
    if not REPORTS_DIR.exists():
        return None
    for f in sorted(REPORTS_DIR.glob(f"{label}_*.json"), reverse=True):
        try:
            with open(f) as fh:
                data = json.load(fh)
            if data.get("sections"):
                return data["sections"]
        except (json.JSONDecodeError, OSError):
            continue
    return None


def generate_master_report(use_compositor: bool = None) -> Path:
    """
    Generate the Master Cross-Analysis Report (FY2019–FY2025).
    
    When the Claude Compositor is available (ANTHROPIC_API_KEY set), this
    generates AI-composed forensic narratives for every section — executive
    summary, year-by-year analysis, violation threads, pattern analyses,
    and regulatory recommendations.
    
    Falls back to mechanical generation when the Compositor is unavailable.
    """
    # Determine whether to use Compositor
    if use_compositor is None:
        use_compositor = COMPOSITOR_AVAILABLE

    db = load_anomaly_db()
    inv = load_deliverable_inventory()
    anomalies = db.get("anomalies", [])
    patterns = db.get("patterns", [])

    doc = Document()
    now = datetime.now().strftime("%B %d, %Y")

    # Title page
    add_title_page(
        doc,
        title="MASTER CROSS-ANALYSIS REPORT",
        subtitle="Nike, Inc. — Seven-Year Forensic Intelligence Compilation\nFY2019 through Q1 CY2026",
        date=now,
    )

    structural = [a for a in anomalies if a.get("severity") == "STRUCTURAL"]
    high = [a for a in anomalies if a.get("severity") == "HIGH"]
    medium = [a for a in anomalies if a.get("severity") == "MEDIUM"]

    # ═══════════════════════════════════════
    # AI-COMPOSED PATH (Claude Compositor)
    # ═══════════════════════════════════════
    if use_compositor:
        print("  [REPORT] Using Claude Compositor for AI-powered narrative synthesis...")
        compositor = ClaudeCompositor()

        # Check for pre-composed sections first
        precomposed = _load_precomposed("master_narrative")
        if precomposed:
            print("  [REPORT] Found pre-composed master narrative — using cached composition.")
            composed = precomposed
        else:
            print("  [REPORT] Composing fresh master narrative via Claude...")
            composed = compositor.compose_full_master_narrative()
            compositor.save_composition(composed, "master_narrative")

        # I. Executive Summary (AI-composed)
        doc.add_heading("Executive Summary", level=1)
        if "executive_summary" in composed:
            _render_composed_text(doc, composed["executive_summary"])
        else:
            doc.add_paragraph(
                f"[Compositor fallback] {len(anomalies)} anomalies, "
                f"{len(patterns)} compounding patterns identified."
            )

        # II. Seven-Year Investigation Arc (AI-composed)
        doc.add_page_break()
        doc.add_heading("Seven-Year Investigation Arc", level=1)
        if "investigation_arc" in composed:
            _render_composed_text(doc, composed["investigation_arc"])

        # III. Year-by-Year Findings (AI-composed per fiscal year)
        doc.add_page_break()
        doc.add_heading("Year-by-Year Findings", level=1)
        fiscal_years = ["FY2019", "FY2020", "FY2021", "FY2022",
                        "FY2023", "FY2024", "FY2025"]
        for fy in fiscal_years:
            fy_anomalies = [a for a in anomalies if a.get("fiscal_year") == fy]
            doc.add_heading(f"{fy} — {len(fy_anomalies)} Anomalies", level=2)
            if fy in composed:
                _render_composed_text(doc, composed[fy], heading_level=3)
            elif fy_anomalies:
                for a in fy_anomalies[:10]:
                    doc.add_paragraph(f"[{a['severity']}] {a['title']}", style="List Bullet")
            else:
                doc.add_paragraph("No anomalies recorded for this fiscal year.")

        # IV. Violation Narratives (AI-composed per category)
        doc.add_page_break()
        doc.add_heading("Violation Analysis by Category", level=1)
        violation_narratives = composed.get("violation_narratives", {})
        category_titles = {
            "section_16": "Section 16(a) — Form 4 Timeliness Violations",
            "insider_trading": "Section 10(b) / Rule 10b-5 — Insider Trading Patterns",
            "swoosh_13d": "Section 13(d) — Schedule 13D Chronic Staleness",
            "exhibit": "Regulation S-K — Exhibit Disclosure Issues",
            "disclosure_pattern": "Section 14(a) — Proxy Disclosure Patterns",
        }
        for cat_key, cat_title in category_titles.items():
            if cat_key in violation_narratives:
                doc.add_heading(cat_title, level=2)
                _render_composed_text(doc, violation_narratives[cat_key], heading_level=3)
            else:
                cat_anomalies = [a for a in anomalies if a.get("category") == cat_key]
                if cat_anomalies:
                    doc.add_heading(cat_title, level=2)
                    add_anomaly_table(doc, cat_anomalies)

        # V. Compounding Pattern Analyses (AI-composed per pattern)
        doc.add_page_break()
        doc.add_heading("Compounding Patterns", level=1)
        pattern_narratives = composed.get("pattern_narratives", {})
        for pattern in patterns:
            pid = pattern.get("pattern_id", "")
            doc.add_heading(f"{pid}: {pattern.get('title', '')}", level=2)
            if pid in pattern_narratives:
                _render_composed_text(doc, pattern_narratives[pid], heading_level=3)
            else:
                doc.add_paragraph(pattern.get("description", ""))

        # VI. Regulatory Recommendation Matrix (AI-composed)
        doc.add_page_break()
        doc.add_heading("Regulatory Recommendation Matrix", level=1)
        if "regulatory_matrix" in composed:
            _render_composed_text(doc, composed["regulatory_matrix"])

        # VII. Full Anomaly Catalog (mechanical — always exact)
        doc.add_page_break()
        add_anomaly_table(doc, anomalies, "Complete Anomaly Catalog")

        # VIII. Evidence Index
        doc.add_heading("Evidence Index", level=1)
        doc.add_paragraph(
            "All anomalies are supported by specific EDGAR accession numbers, "
            "filing dates, and transaction-level data. The anomaly database "
            f"({ANOMALY_DIR / 'anomaly_database.json'}) contains machine-readable "
            "evidence records for every finding in this report."
        )

    # ═══════════════════════════════════════
    # MECHANICAL PATH (No API key / fallback)
    # ═══════════════════════════════════════
    else:
        print("  [REPORT] Using mechanical generation (no Compositor)...")

        # Executive summary
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(
            f"This report synthesizes findings from a seven-year forensic investigation "
            f"of Nike, Inc. (CIK 0000320187) spanning FY2019 through Q1 CY2026. "
            f"The investigation identified {len(anomalies)} discrete anomalies organized into "
            f"{len(patterns)} compounding patterns.\n\n"
            f"Severity breakdown:\n"
            f"  • STRUCTURAL: {len(structural)} (systemic governance/compliance failures)\n"
            f"  • HIGH: {len(high)} (material regulatory violations)\n"
            f"  • MEDIUM: {len(medium)} (significant discrepancies requiring documentation)\n\n"
            f"Source material: {inv.get('total_deliverables', 'N/A')} professional deliverables "
            f"plus parsed EDGAR filing data."
        )

        # Year-by-year analysis
        doc.add_heading("Year-by-Year Findings", level=1)
        fiscal_years = ["FY2019", "FY2020", "FY2021", "FY2022",
                        "FY2023", "FY2024", "FY2025"]
        for fy in fiscal_years:
            fy_anomalies = [a for a in anomalies if a.get("fiscal_year") == fy]
            doc.add_heading(f"{fy} — {len(fy_anomalies)} Anomalies", level=2)
            if fy_anomalies:
                for a in fy_anomalies[:10]:
                    doc.add_paragraph(
                        f"[{a['severity']}] {a['title']}", style="List Bullet",
                    )
                    if a.get("description"):
                        doc.add_paragraph(a["description"][:300])
            else:
                doc.add_paragraph("No anomalies recorded for this fiscal year.")

        # Compounding patterns
        add_pattern_section(doc, patterns, anomalies)

        # Full anomaly catalog
        doc.add_page_break()
        add_anomaly_table(doc, anomalies, "Complete Anomaly Catalog")

        # Evidence index
        doc.add_heading("Evidence Index", level=1)
        doc.add_paragraph(
            "All anomalies are supported by specific EDGAR accession numbers, "
            "filing dates, and transaction-level data. See the anomaly database "
            "for machine-readable evidence records."
        )

    # Save
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = REPORTS_DIR / f"Master_Cross_Analysis_{datetime.now().strftime('%Y%m%d')}.docx"
    doc.save(output_path)

    return output_path


def generate_sec_bundle() -> Path:
    """
    Generate the SEC Division of Enforcement submission bundle.
    Organized by violation type with exact statutory references.
    """
    db = load_anomaly_db()
    anomalies = db.get("anomalies", [])
    patterns = db.get("patterns", [])

    doc = Document()
    now = datetime.now().strftime("%B %d, %Y")

    add_title_page(
        doc,
        title="SEC ENFORCEMENT EVIDENCE BUNDLE",
        subtitle="Division of Enforcement — Tips, Complaints, and Referrals\nNike, Inc. (CIK 0000320187)",
        date=now,
        classification="PRIVILEGED & CONFIDENTIAL — ATTORNEY WORK PRODUCT",
    )

    # Cover letter
    doc.add_heading("Cover Letter", level=1)
    doc.add_paragraph(
        f"Dear SEC Division of Enforcement,\n\n"
        f"This submission presents evidence of multiple securities law violations "
        f"by Nike, Inc. and certain of its officers and directors, identified through "
        f"a systematic seven-year forensic analysis of SEC EDGAR filings spanning "
        f"FY2019 through Q1 CY2026.\n\n"
        f"The investigation identified {len(anomalies)} discrete anomalies organized "
        f"into {len(patterns)} compounding patterns, including potential violations of:\n"
    )

    # Statutory references
    statutes = [
        "Section 10(b) of the Securities Exchange Act of 1934 and Rule 10b-5",
        "Section 13(d) of the Exchange Act (Schedule 13D amendment obligations)",
        "Section 16(a) of the Exchange Act (Form 4 timeliness)",
        "Section 14(a) of the Exchange Act (proxy statement disclosure)",
        "Rule 16a-3(g) (2 business day filing deadline)",
        "Regulation S-K Item 601 (exhibit filing requirements)",
        "Rule 13d-2 (prompt amendment of Schedule 13D)",
    ]
    for statute in statutes:
        doc.add_paragraph(f"  • {statute}", style="List Bullet")

    # Evidence by violation type
    doc.add_heading("Evidence by Violation Type", level=1)

    categories = {
        "section_16": "Section 16(a) — Late Form 4 Filings",
        "insider_trading": "Section 10(b) / Rule 10b-5 — Insider Trading Patterns",
        "swoosh_13d": "Section 13(d) — Schedule 13D Staleness",
        "exhibit": "Regulation S-K — Exhibit Disclosure Issues",
        "disclosure_pattern": "Section 14(a) — Proxy Disclosure Patterns",
    }

    for cat_key, cat_title in categories.items():
        cat_anomalies = [a for a in anomalies if a.get("category") == cat_key]
        if cat_anomalies:
            doc.add_heading(cat_title, level=2)
            add_anomaly_table(doc, cat_anomalies, f"{cat_title} — Evidence Summary")
            for a in cat_anomalies[:5]:
                doc.add_paragraph(f"\n{a['anomaly_id']}: {a['title']}")
                doc.add_paragraph(a.get("description", ""))
                if a.get("evidence"):
                    for ev in a["evidence"]:
                        doc.add_paragraph(f"  — {ev}", style="List Bullet")

    # Pattern analysis
    add_pattern_section(doc, patterns, anomalies)

    # Recommended enforcement actions
    doc.add_heading("Recommended Enforcement Actions", level=1)
    doc.add_paragraph(
        "Based on the evidence presented, the following enforcement actions are recommended:\n\n"
        "1. Formal investigation of insider trading patterns under Section 10(b)\n"
        "2. Enforcement action for Section 16(a) filing delinquencies\n"
        "3. Compelled amendment of stale Schedule 13D filings\n"
        "4. Review of insider trading policy (Exhibit 19) self-approval mechanism\n"
        "5. Examination of proxy statement disclosure accuracy under Section 14(a)"
    )

    # Save
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = REPORTS_DIR / f"SEC_Enforcement_Bundle_{datetime.now().strftime('%Y%m%d')}.docx"
    doc.save(output_path)

    return output_path


def generate_doj_referral() -> Path:
    """
    Generate DOJ Fraud Section criminal referral package.
    """
    db = load_anomaly_db()
    anomalies = db.get("anomalies", [])
    patterns = db.get("patterns", [])

    doc = Document()
    now = datetime.now().strftime("%B %d, %Y")

    add_title_page(
        doc,
        title="DOJ CRIMINAL REFERRAL PACKAGE",
        subtitle="Fraud Section — Securities Fraud Investigation\nNike, Inc. (CIK 0000320187)",
        date=now,
        classification="PRIVILEGED & CONFIDENTIAL — ATTORNEY WORK PRODUCT",
    )

    # Referral letter
    doc.add_heading("Criminal Referral Letter", level=1)

    structural = [a for a in anomalies if a.get("severity") == "STRUCTURAL"]
    high_severity = [a for a in anomalies
                     if a.get("severity") in ("STRUCTURAL", "HIGH")
                     and a.get("category") in ("insider_trading", "section_16")]

    doc.add_paragraph(
        f"This criminal referral presents evidence of potential securities fraud "
        f"by officers and directors of Nike, Inc. identified through forensic "
        f"analysis of seven years of SEC EDGAR filings.\n\n"
        f"The investigation identified {len(structural)} structural governance failures "
        f"and {len(high_severity)} high-severity anomalies warranting criminal investigation."
    )

    # Securities fraud pattern
    doc.add_heading("Securities Fraud Pattern Summary", level=1)
    insider_anomalies = [a for a in anomalies if a.get("category") == "insider_trading"]
    if insider_anomalies:
        for a in insider_anomalies:
            doc.add_heading(a["title"], level=2)
            doc.add_paragraph(a.get("description", ""))
            if a.get("evidence"):
                for ev in a["evidence"]:
                    doc.add_paragraph(f"  — {ev}", style="List Bullet")

    # Pre-clearance analysis
    doc.add_heading("Pre-Clearance Self-Approval Analysis", level=1)
    doc.add_paragraph(
        "The Nike Exhibit 19.2 Blackout and Pre-clearance Policy contains provisions "
        "that may allow the Chairman/CEO to effectively self-approve insider trades. "
        "This structural vulnerability, combined with cumulative selling patterns, "
        "warrants investigation under Section 10(b) and Rule 10b-5."
    )

    # Timeline
    doc.add_heading("Chronological Evidence Timeline", level=1)
    for a in sorted(anomalies, key=lambda x: x.get("fiscal_year", "")):
        if a.get("severity") in ("STRUCTURAL", "HIGH"):
            doc.add_paragraph(
                f"[{a['fiscal_year']}] {a['title']}",
                style="List Bullet",
            )

    # Save
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = REPORTS_DIR / f"DOJ_Criminal_Referral_{datetime.now().strftime('%Y%m%d')}.docx"
    doc.save(output_path)

    return output_path


def generate_legislative_brief() -> Path:
    """
    Generate Congressional legislative briefing package.
    """
    db = load_anomaly_db()
    anomalies = db.get("anomalies", [])
    patterns = db.get("patterns", [])

    doc = Document()
    now = datetime.now().strftime("%B %d, %Y")

    add_title_page(
        doc,
        title="LEGISLATIVE BRIEFING PACKAGE",
        subtitle="Senate Banking Committee / House Financial Services Committee\nNike, Inc. — Governance Case Study",
        date=now,
        classification="CONFIDENTIAL",
    )

    # One-page executive summary
    doc.add_heading("Executive Summary", level=1)
    doc.add_paragraph(
        f"This briefing presents findings from a seven-year forensic investigation "
        f"of Nike, Inc. that reveal systemic governance and disclosure failures "
        f"relevant to current legislative proposals on insider trading reform, "
        f"beneficial ownership transparency, and corporate governance standards.\n\n"
        f"Key findings: {len(anomalies)} anomalies across {len(patterns)} compounding patterns."
    )

    # Governance case study
    doc.add_heading("Dual-Class Governance Case Study", level=1)
    doc.add_paragraph(
        "Nike's dual-class share structure (Class A: 1 vote, Class B: institutional; "
        "controlled via Swoosh, LLC) provides a case study in concentrated voting power, "
        "limited accountability, and disclosure opacity."
    )

    # Regulatory gap analysis
    doc.add_heading("Regulatory Gap Analysis", level=1)
    doc.add_paragraph(
        "The investigation identified a 14-year gap in SEC correspondence with Nike "
        "(no CORRESP filings from approximately 2010 to 2024), suggesting insufficient "
        "regulatory oversight of one of the largest publicly traded companies."
    )

    # Recommended reforms
    doc.add_heading("Recommended Legislative Reforms", level=1)
    reforms = [
        "Mandatory annual Schedule 13D updates for controlling shareholders",
        "Enhanced insider trading policy disclosure requirements (beyond Exhibit 19)",
        "Pre-clearance process audit requirements for companies with concentrated ownership",
        "Automatic SEC review triggers for companies with 10+ year correspondence gaps",
        "Whistleblower protection enhancements for governance-related complaints",
    ]
    for reform in reforms:
        doc.add_paragraph(reform, style="List Bullet")

    # Full anomaly catalog
    doc.add_page_break()
    add_anomaly_table(doc, anomalies, "Complete Anomaly Catalog")

    # Save
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = REPORTS_DIR / f"Legislative_Briefing_{datetime.now().strftime('%Y%m%d')}.docx"
    doc.save(output_path)

    return output_path


def generate_report(report_type: str) -> Path:
    """Route to the appropriate report generator."""
    generators = {
        "master": generate_master_report,
        "sec": generate_sec_bundle,
        "doj": generate_doj_referral,
        "leg": generate_legislative_brief,
        "legislative": generate_legislative_brief,
    }

    gen = generators.get(report_type.lower())
    if not gen:
        raise ValueError(f"Unknown report type: {report_type}. "
                         f"Available: {', '.join(generators.keys())}")

    output_path = gen()
    print(f"\n  ✓ Report generated: {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(description="JLAW Report Generator Agent")
    parser.add_argument("--type", type=str, required=True,
                        choices=["master", "sec", "doj", "leg", "legislative"],
                        help="Report type to generate")

    args = parser.parse_args()

    print(f"\n{'='*60}")
    print(f"  JLAW REPORT GENERATOR — {args.type.upper()}")
    print(f"  Started: {datetime.now().isoformat()}")
    print(f"{'='*60}\n")

    output = generate_report(args.type)

    print(f"\n{'='*60}")
    print(f"  REPORT GENERATION COMPLETE")
    print(f"  Output: {output}")
    print(f"  Size: {output.stat().st_size / 1024:.1f} KB")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
